# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.luks.devices = {
    luksroot = {
      device = "/dev/disk/by-partuuid/d6f267a1-e082-0f45-9396-ba56d9274c32";
      allowDiscards = true;
      preLVM = true;
    };
  };

  boot.loader.grub.device = "/dev/disk/by-partuuid/ca2e3d9e-c592-b143-8a54-34a040c9c56a";

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "uas" "sd_mod" "rtsx_pci_sdmmc" "aesni_intel" "cryptd" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/3115b5cc-c805-4273-911e-ee295e750842";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/9E60-5295";
      fsType = "vfat";
    };

  swapDevices =
    [{
      device = "/dev/disk/by-uuid/6f516e43-0318-4559-b48e-b3243ea6befe";
      priority = 1;
    }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
